WebMVC/Controllers/LoginController.cs
using Application.Models;
using Domain.Entity;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    public class LoginController : Controller
    {
        #region Private member
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<Role> _roleManager;
        private readonly SignInManager<User> _signInManager;
        private readonly IConfiguration _configuration;
        public IList<AuthenticationScheme> ExternalLogins { get; set; }
        private UserInforModel userInforModel { get; set; } = new UserInforModel();
        private bool _isLogin { get; set; } = true;
        #endregion

        #region Default contructor
        public LoginController(UserManager<User> userManager,
           RoleManager<Role> roleManager,
           IConfiguration configuration,
           SignInManager<User> signInManager
           
           )
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _configuration = configuration;
            _signInManager = signInManager;
        }
        #endregion

        #region Login 
        // GET: LoginController
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        /// <summary>
        /// Login with <see cref="LoginModel"/>
        /// </summary>
        /// <param name="userLogin">user login model</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Login(LoginModel userLogin)
        {
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
               
                var signInResult =
                    await _signInManager.PasswordSignInAsync(userLogin.UserName, userLogin.Password, false, lockoutOnFailure: false);
            }
            return View();
        }
        #endregion

        #region Log Out 
        /// <summary>
        /// Log out user sign in 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            userInforModel = null;
            return RedirectToAction("Index", "Home");
        }
        #endregion

        #region CRUD User

        /// <summary>
        /// Get view create 
        /// </summary>
        /// <returns></returns>
        // GET: LoginController/Create
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Post create  new user by <see cref="RegisterModel"/> 
        /// </summary>
        /// <param name="register">model create new user</param>
        /// <returns></returns>
        // POST: LoginController/Create
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RegisterModel register)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }
            // check user exist
            var userExist = await _userManager.FindByEmailAsync(register.Email);
            if (userExist != null)
            {
                return RedirectToAction("Index");
            }
            User user = new()
            {
                UserName = register.UserName,
                Email = register.Email,
                Password = register.Password,
                FirstName = register.FirstName,
                LastName = register.LastName,
                PhoneNumber = register.PhoneNumber,
                SecurityStamp = Guid.NewGuid().ToString(),
            };
            if (await _roleManager.RoleExistsAsync("User"))
            {
                // add user the database
                var result = await _userManager.CreateAsync(user, register.Password);
                if (result.Succeeded)
                {
                    // assign role
                    var checkAddRole = await _userManager.AddToRoleAsync(user, "User");
                    if (checkAddRole.Succeeded)
                    {
                        return RedirectToAction("Home");
                    }
                }
            }
            return View();
        }
        /// <summary>
        /// Get detail user by user id
        /// </summary>
        /// <param name="id">user id</param>
        /// <returns></returns>
        // GET: LoginController/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        /// <summary>
        /// Get user by <see cref="int"/> id
        /// </summary>
        /// <param name="id">User id</param>
        /// <returns></returns>
        // GET: LoginController/Edit/5
        public IActionResult Edit(int id)
        {
            return View();
        }


        /// <summary>
        /// Submit <see cref="IFormCollection"/> user with <see cref="int"/> userId  after edit
        /// </summary>
        /// <param name="id">user id</param>
        /// <param name="collection"></param>
        /// <returns></returns>
        // POST: LoginController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// Get user by <see cref="int"/> userId
        /// </summary>
        /// <param name="id">userid</param>
        /// <returns></returns>
        // GET: LoginController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

      
        /// <summary>
        /// Delete <see cref="IFormCollection"/> User with <see cref="int"/> userId
        /// </summary>
        /// <param name="id">user id</param>
        /// <param name="collection">user infor</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #region Access denied view
        public IActionResult AccessDenied()
        {
            return View();
        }
        #endregion
    }
}

WebMVC/Controllers/ProductController.cs
using Application.Models;
using Application.Services;
using Application.Services.Implements;
using AutoMapper;
using Domain.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebMVC.Controllers
{
    
    public class ProductController : Controller
    {
        private readonly IProductService _productServices;
        private readonly IMapper _mapper;
        //private readonly ILogger<ProductController> _logger;
        public ProductController(IProductService productServices, IMapper mapper, ILogger<ProductController> logger)
        {
            _productServices = productServices;
            _mapper = mapper;
           // _logger = logger;
        }

        // GET: ProductController
      //  [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var products = _productServices.FindAll().ToList();
            //var products = _productServices.GetAllProduct();
            return View(products);
        }

        // GET: ProductController/Details/5
        public ActionResult Details(string id)
        {
            var product = _productServices.GetProducBytId(id);
            return View(product);
        }

        // GET: ProductController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var productObj = new Product
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = collection["Name"],  // Sử dụng chỉ mục để lấy giá trị từ form
                    Price = decimal.TryParse(collection["Price"], out decimal price) ? price : 0,  // Chuyển đổi sang decimal
                    Description = collection["Description"],
                    DeleteFlag =  0, //Int32.Parse(collection["DeleteFlag"]),
                    //DeleteFlag = bool.TryParse(collection["DeleteFlag"], out bool deleteFlag) ? deleteFlag : false,  // Chuyển đổi sang bool
                    UpdatedDate = DateTime.Now,
                    CreatedDate = DateTime.Now
                };
                _productServices.Create(productObj);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(string id)
        {
            var productObj = _productServices.GetProducBytId(id);
            return View(productObj);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, ProductModel productModel)
        {
            try
            {
                var productObj = _productServices.GetProducBytId(id);
                if (productObj == null)
                {
                    return NotFound("Product not found.");
                }
                productObj.Name = productModel.Name;
                productObj.Price =  productModel.Price;
                productObj.Description = productModel.Description;
                _productServices.Update(productObj);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Delete/5
        public IActionResult Delete(string id)
        {
            if(!ModelState.IsValid)
            {
                return NotFound();
            }
            Product productObj = _productServices.GetProducBytId(id);
            return View(productObj);
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id, IFormCollection collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    return NotFound("Product not found.");
                }
                var product = _productServices.GetProducBytId(id);

                _productServices.Delete(product);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebMVC/Views/Shared/_Layout.cshtml
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                       
                            @if(SignInManager.IsSignedIn(User))
                            {
                                var user = await UserManager.GetUserAsync(User);
                                string fullName = user.FirstName + " " + user.LastName;
                                <li class="nav-item">
                                    <span>Hello @fullName </span>
                                </li>
                                <li class="nav-item">
                                    <form method="post" asp-controller="Login" asp-action="LogOut">
                                        <button type="submit" class="nav-link btn btn-link py-0">
                                                Sign out
                                        </button>
                                    </form>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login" asp-route-returnUrl="@Context.Request.Path">Sign in</a>
                                </li>
                                <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                            }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>